### ISSUE TITLE
vod sections in embed 

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#13]
### Repository

Mops-Bot

### Is your feature request related to a specific problem?

N/A

### What solution would you like to see?

Addition of vod sections containing game change ( with time stamp and link to section in VOD ) 

- Just check for if current category has changed since last api call

**Comment by OnlyTunes** [comment]
This will be added in addition to the graph ( data is contained in the same resp as the graph stuff )

**Comment by CaldeiraG** [comment]
Duplicate of https://github.com/OnlyTunesRadio/Mops-Reports/issues/45
