### ISSUE TITLE
Addition: Add a list of Guilds currently using Mops Bot 

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#20]
### Repository

Mops-Bot-Site

### Is your feature request related to a specific problem?

N/A

### What solution would you like to see?

Addition of servers using MopsBot with user count in the guild + possibly a quote if guild owner wants to specify something might also be good for if we have partnered guilds for MopsBot

**Comment by CaldeiraG** [comment]
How can we grab the number of guilds / users that the bot is in? Discord APIs?

**Comment by OnlyTunes** [comment]
number of guilds / users will be done through our api ( /bot/{type} *type can be guilds / channels / users* ) and i can add an endpoint that returns all values if needed to save on reqs

**Comment by CaldeiraG** [comment]
An endpoint that returns it all sounds good as it will make use of Vuex for caching purposes

**Comment by OnlyTunes** [comment]
cool will add it in a min

**Comment by OnlyTunes** [comment]
turns out its always had an endpoint to return all i was just being stupid ( `/bot/info` )

```
type botInfo struct {
	TotalGuilds   int
	TotalTrackers int
	TotalUsers    int
	TotalChannels int
	Latency       int
}
```

**Comment by CaldeiraG** [comment]
Total guilds/users is done (see commit https://github.com/OnlyTunesRadio/Mops-Bot-Site/commit/39d4346c76bd132b43df7a56e8de746208d0fcd1), adding total trackers will be added ASAP

**Comment by OnlyTunes** [comment]
closing due to this being completed now on the site
