### ISSUE TITLE
Addition:  Add full commands list to the site!

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#21]
### Repository

Mops-Bot-Site

### Is your feature request related to a specific problem?

N/A

### What solution would you like to see?

Add full commands list with a way to jump to a category via the URL ( mopsbot.com/commands#trackers ) also make it so if you click into a command it shows a popup with more in depth info about said command and an image of usage

**Comment by OnlyTunes** [comment]
in progress VIA @CaldeiraG however there seems to be issues with VUE store

**Comment by CaldeiraG** [comment]
The table now works with Vuex store (see commit https://github.com/OnlyTunesRadio/Mops-Bot-Site/commit/18ae71cf255cdbdc8dab22fee976bfdd60e29e11) but needs category filtering

**Comment by CaldeiraG** [comment]
Fixed (see commit https://github.com/OnlyTunesRadio/Mops-Bot-Site/commit/d1ee67b7e835e75191533cd3b92f8104c66673ed)
