### ISSUE TITLE
Site Commands list doesnt show on mobile versions

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#57]
### Repository

Mops-Bot-Site

### Bug type

Other

### Description of the bug?

Info from user: Commands list doesnt seem to work on mobile... had to move to pc for it too show and work properly. ( INVESTIGATION NEEDED FOR BUG )

**Comment by CaldeiraG** [comment]
Commands page needs a different layout to make it usable

 There's no link to go to the commands page from mobile menu

Add mops logo on app-bar to go back to homepage if you're on commands page

Should be patched later today

**Comment by CaldeiraG** [comment]
Fixed (see commit https://github.com/OnlyTunesRadio/Mops-Bot-Site/commit/23610ecf24c655353f4836784044b7dd97f478f0)
