### ISSUE TITLE
Animate the currently used counts

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#58]
### Repository

Mops-Bot-Site

### Is your feature request related to a specific problem?

N/A

### What solution would you like to see?

Make an animation which will quickly count up to the max values on the site

**Comment by CaldeiraG** [comment]
Just found this: https://github.com/xlsdg/vue-countup-v2

Should be easy enough to do

**Comment by CaldeiraG** [comment]
Fixed (https://github.com/OnlyTunesRadio/Mops-Bot-Site/commit/23610ecf24c655353f4836784044b7dd97f478f0)
