### ISSUE TITLE
Site urls /dashboard/* needs coming soon page added

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#60]
### Repository

Mops-Bot-Site

### Bug type

Other

### Description of the bug?

website needs all /dashboard/* routes to return a coming soon page currently

**Comment by CaldeiraG** [comment]
Fixed (see commit https://github.com/OnlyTunesRadio/Mops-Bot-Site/commit/23610ecf24c655353f4836784044b7dd97f478f0)
