### ISSUE TITLE
wip.mopsbot.com doesn't redirect HTTP to HTTPS - NGINX

### ISSUE THREAD

**Issue by CaldeiraG** [OnlyTunesRadio/Mops-Reports#66]
### Repository

Mops-Bot-Site

### Description of the bug?

http://wip.mopsbot.com is not redirecting to HTTPS causing it to return a 404 error. Nginx issue

**Comment by OnlyTunes** [comment]
Issue fixed in latest config update.  turns out nginx ignores if checks now 

Will update main site config shortly
