### ISSUE TITLE
CheerUp command 

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#71]
### Repository

Mops-Bot

### Is your feature request related to a specific problem?

N/A

### What solution would you like to see?

cheerup cmd for people having a bad day

**Comment by OnlyTunes** [comment]
assigned @CaldeiraG as its a simple thing kek

**Comment by OnlyTunes** [comment]
i created the file and the basics of it ( just need quotes now )

**Comment by CaldeiraG** [comment]
Yoinking this website https://www.wishesmsg.com/cheer-up-messages-quotes/ x)

**Comment by CaldeiraG** [comment]
Mr. Cal did it, it's roughly working KEK
