### ISSUE TITLE
Youtube trackers showing up on yt_config but not tracked_yt_channels

### ISSUE THREAD

**Issue by CaldeiraG** [OnlyTunesRadio/Mops-Reports#78]
### Repository

Mops-Bot-API

### Description of the bug?

API adds tracking config to DB but nothing shows up in the tracked_yt_channels table.

![Table](https://cdn.discordapp.com/attachments/795088560838410290/1013607554301046884/unknown.png)

**Comment by OnlyTunes** [comment]
issue fixed
