### ISSUE TITLE
Slash Command update warning once per user

### ISSUE THREAD

**Issue by OnlyTunes** [OnlyTunesRadio/Mops-Reports#86]
### Repository

Mops-Bot

### Bug type

Commands

### Description of the bug?

bonk stop using mops to spam with ! marks 🤦

**Comment by CaldeiraG** [comment]
lmao

**Comment by OnlyTunes** [comment]
added container should have been built by now

**Comment by OnlyTunes** [comment]
Creates multiple records so additional debugging is needed

**Comment by OnlyTunes** [comment]
added logging for testing

**Comment by OnlyTunes** [comment]
completed and working
